spring.application.name=demo
server.port=8082

spring.mongodb.uri=mongodb+srv://211182_db_user:WpsoT9w9n8zjwnEr@cluster0.ioumynv.mongodb.net/?appName=Cluster0
# Formato recomendado (SRV)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG