spring.application.name=demo
server.port=8082

spring.mongodb.uri=mongodb+srv://jerzy191219:jerzy191219@cluster0.amsksv7.mongodb.net/?appName=Cluster0
# Formato recomendado (SRV)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG